title: Legacy Console R&D Wikipedia
description: A general purpose Minecraft Legacy Console Wikipedia, including everything from modding to game details. 
theme: just-the-docs

url: https://lcerd.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
