title: Legacy Console R&D Wiki
description: A general purpose Minecraft Legacy Console Wiki with an emphasis on modding. 
theme: just-the-docs

url: https://lcerd.github.io

color_scheme: dark

aux_links:
  Discord: https://discord.gg/zRDY32WMfs
  GitHub: https://github.com/LCERD/Wiki
